(function(){
  const d=window.PORTFOLIO_DATA; const $=(s)=>document.querySelector(s); const esc=(v)=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const aero=$('[data-aero-shards]'); if(aero){const shardCount=44; aero.innerHTML=Array.from({length:shardCount},(_,i)=>`<i class="aero-shard" style="--i:${i};--x:${Math.round(Math.random()*100)}%;--y:${Math.round(Math.random()*100)}%;--size:${Math.round(18+Math.random()*74)}px;--delay:${(-Math.random()*14).toFixed(2)}s;--duration:${(10+Math.random()*16).toFixed(2)}s;--drift:${Math.round(-140+Math.random()*280)}px;--spin:${Math.round(-45+Math.random()*90)}deg;--alpha:${(.07+Math.random()*.16).toFixed(2)}"></i>`).join('');window.addEventListener('pointermove',e=>{aero.style.setProperty('--pointer-x',`${e.clientX}px`);aero.style.setProperty('--pointer-y',`${e.clientY}px`)});}
  document.title=`${d.site.name}｜个人作品集`; document.querySelector('[data-year]').textContent=d.site.year; document.querySelector('[data-brand]').textContent=d.site.brand;
  Object.entries({'[data-hero-kicker]':d.hero.kicker,'[data-hero-overline]':d.hero.overline,'[data-hero-title]':d.hero.title,'[data-hero-intro]':d.hero.intro,'[data-hero-location]':d.hero.location,'[data-hero-note]':d.hero.note,'[data-about-lead]':d.about.lead,'[data-contact-copy]':d.contact.copy,'[data-footer-name]':d.site.name}).forEach(([s,v])=>$(s).textContent=v);
  $('[data-email]').textContent=d.contact.email; $('[data-email]').href=`mailto:${d.contact.email}`;
  const profile=d.profile; const mount=$('[data-profile-card]');
  mount.innerHTML=`<div class="profile-card-wrap"><div class="profile-card-glow"></div><article class="profile-card"><div class="profile-card-shine"></div><img class="profile-avatar" src="${esc(profile.avatar)}" alt="${esc(profile.name)}"><div class="profile-title"><h3>${esc(profile.name)}</h3><p>${esc(profile.title)}</p></div><div class="profile-bottom"><div><strong>@${esc(profile.handle)}</strong><span><i></i>${esc(profile.status)}</span></div><a href="mailto:${esc(d.site.email)}">${esc(profile.contactText)} ↗</a></div></article></div><div class="profile-facts">${profile.facts.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`;
  const profileWrap=mount.querySelector('.profile-card-wrap'), profileCard=mount.querySelector('.profile-card');
  profileWrap.addEventListener('pointermove',e=>{const r=profileCard.getBoundingClientRect();const x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;profileCard.style.setProperty('--rx',`${(0.5-y)*12}deg`);profileCard.style.setProperty('--ry',`${(x-0.5)*14}deg`);profileCard.style.setProperty('--px',`${x*100}%`);profileCard.style.setProperty('--py',`${y*100}%`);profileWrap.classList.add('is-active')});
  profileWrap.addEventListener('pointerleave',()=>{profileCard.style.setProperty('--rx','0deg');profileCard.style.setProperty('--ry','0deg');profileCard.style.setProperty('--px','50%');profileCard.style.setProperty('--py','50%');profileWrap.classList.remove('is-active')});
  $('[data-stats]').innerHTML=d.stats.map(x=>`<div class="stat"><strong>${esc(x.value)}</strong><span>${esc(x.label)}</span></div>`).join('');
  const shuffle=(items)=>{const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
  const rolling=$('[data-rolling-gallery]'); if(rolling){const shuffled=shuffle(d.showcaseImages);rolling.innerHTML=[0,1,2].map((row)=>{const rowItems=shuffled.slice(row*8,row*8+10);const repeated=[...rowItems,...rowItems];return `<div class="rolling-row row-${row+1}"><div class="rolling-track">${repeated.map((src,i)=>`<figure><img src="${esc(src)}" alt="作品展示图 ${i+1}" loading="lazy"></figure>`).join('')}</div></div>`}).join('');}
  const openImageGallery=(images,title)=>{if(!images?.length)return;const viewer=document.createElement('dialog');viewer.className='gallery-dialog';viewer.innerHTML=`<button aria-label="关闭">×</button><div class="dialog-title">${esc(title||'作品图集')}</div><div class="dialog-grid">${images.map((src,i)=>`<img src="${esc(src)}" alt="${esc(title||'作品图集')} ${i+1}" loading="lazy">`).join('')}</div>`;document.body.appendChild(viewer);viewer.showModal();viewer.querySelector('button').onclick=()=>viewer.close();viewer.addEventListener('close',()=>viewer.remove());};
  const accordion=$('[data-accordion-gallery]');
  if(accordion){
    let active=2; const items=d.visualAccordion; accordion.innerHTML=`<div class="accordion-gallery" role="list" aria-label="视觉作品图集">${items.map((item,i)=>`<a class="ag-panel${i===active?' ag-panel--active':''}" href="#visual" role="listitem" tabindex="0" data-index="${i}"><span class="ag-panel__frame"><span class="ag-panel__media"><img src="${esc(item.image)}" alt="${esc(item.alt||item.label)}" loading="lazy"></span><span class="ag-panel__overlay"></span></span><span class="ag-panel__label"><span class="ag-panel__bar"></span><span class="ag-panel__text">${esc(item.label)}</span></span></a>`).join('')}</div>`;
    const panels=[...accordion.querySelectorAll('.ag-panel')]; const apply=(next)=>{active=next;panels.forEach((panel,i)=>{panel.classList.toggle('ag-panel--active',i===active);panel.style.setProperty('--ag-order',i-active);});}; panels.forEach((panel,i)=>{panel.addEventListener('mouseenter',()=>apply(i));panel.addEventListener('focus',()=>apply(i));panel.addEventListener('click',e=>{if(i!==active){e.preventDefault();apply(i)}else{e.preventDefault();openImageGallery(items[i].gallery,items[i].label)}});panel.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowDown'){e.preventDefault();apply((i+1)%panels.length);panels[(i+1)%panels.length].focus()}if(e.key==='ArrowLeft'||e.key==='ArrowUp'){e.preventDefault();apply((i-1+panels.length)%panels.length);panels[(i-1+panels.length)%panels.length].focus()}if(e.key==='Enter'){e.preventDefault();openImageGallery(items[i].gallery,items[i].label)}})});apply(active);
  }
  const media=(x,video=false)=>{if(!x)return '<div class="empty-media">Coming Soon / 暂未上线</div>';return video&&x.mode==='local'?`<video controls preload="metadata" poster="${esc(x.poster||'')}" src="${esc(x.src)}"></video>`:video&&x.mode==='embed'?`<iframe src="${esc(x.src)}" title="Embedded video" loading="lazy" allowfullscreen></iframe>`:`<img src="${esc(x)}" alt="" loading="lazy">`};
  const workMedia=(w)=>{const v=w.video;if(!v)return media(w.thumb);if(v.mode==='local')return `<video controls preload="metadata" poster="${esc(w.thumb||'')}" src="${esc(v.src)}"></video>`;if(v.mode==='embed')return `<iframe src="${esc(v.src)}" title="${esc(w.title)} video" loading="lazy" allowfullscreen></iframe>`;if(v.mode==='link')return `<div class="link-media">${media(w.thumb)}<a href="${esc(v.src||'#')}" target="_blank" rel="noreferrer">Open video ↗</a></div>`;return media(w.thumb)};
  const selectedMount=$('[data-selected-works]'); if(selectedMount) selectedMount.innerHTML=d.selectedWorks.map((w,i)=>`<article class="work-card"><div class="media-frame">${workMedia(w)}</div><div class="work-info"><div><h3>${esc(w.title)}</h3><p>${esc(w.description)}</p></div><span class="tag">${esc(w.category)}</span></div></article>`).join('');
  $('[data-film-list]').innerHTML=d.film.map((w,i)=>`<article class="film-row"><span class="number">0${i+1}</span><h3>${esc(w.title)}</h3><p>${esc(w.meta)}</p><span class="role">${esc(w.role)}</span>${w.link?`<a href="${esc(w.link)}" target="_blank" rel="noreferrer">OPEN ↗</a>`:''}</article>`).join('');
  const visualMount=$('[data-visual-list]'); if(visualMount) visualMount.innerHTML=d.visual.map(w=>`<article class="visual-card" tabindex="0"><div class="visual-image"><img src="${esc(w.image)}" alt="${esc(w.title)}" loading="lazy"></div><h3>${esc(w.title)}</h3><p>${esc(w.type)} · click to view gallery</p><div class="lightbox-gallery" hidden>${w.gallery.map(img=>`<img src="${esc(img)}" alt="" loading="lazy">`).join('')}</div></article>`).join('');
  const c=d.caseStudy; $('[data-case-study]').innerHTML=`<div class="case-layout"><div class="case-visual"><img src="${esc(c.image)}" alt="${esc(c.title)}" loading="lazy"></div><div class="case-copy"><span class="status">${esc(c.status)}</span><h3>${esc(c.title)}</h3><p>${esc(c.summary)}</p><p>${esc(c.detail)}</p><div class="case-meta">${c.meta.map(x=>`<div>${esc(x)}</div>`).join('')}</div></div></div><div class="case-gallery-rows">${c.galleryRows.map((row,rowIndex)=>{const repeated=[...row,...row];return `<div class="case-gallery-row case-row-${rowIndex+1}"><div class="case-gallery-track">${repeated.map((x,i)=>`<img src="${esc(x)}" alt="${esc(c.title)} ${rowIndex+1}-${i+1}" loading="lazy">`).join('')}</div></div>`}).join('')}</div>`;
  $('[data-experience]').innerHTML=d.experienceGroups.map(group=>`<section class="experience-group"><div class="experience-group-heading"><span class="group-number">${esc(group.number)}</span><h3>${esc(group.title)}</h3><span class="group-en">${esc(group.en)}</span></div>${group.entries.map(x=>`<article class="timeline-item"><time>${esc(x.time)}</time><div><div class="experience-title-row"><h4>${esc(x.title)}</h4><span class="experience-role">${esc(x.role)}</span></div><p>${esc(x.body)}</p>${x.note?`<small class="experience-note">${esc(x.note)}</small>`:''}</div></article>`).join('')}</section>`).join('');
  $('[data-skills]').innerHTML=d.skills.map(x=>`<div class="skill-group"><h3>${esc(x.name)}</h3><p>${esc(x.items)}</p></div>`).join(''); $('[data-about-body]').innerHTML=`<p>${esc(d.about.body)}</p>`;
  document.querySelectorAll('.visual-card').forEach(card=>card.addEventListener('click',()=>{const imgs=[...card.querySelectorAll('.lightbox-gallery img')]; if(!imgs.length)return; const viewer=document.createElement('dialog'); viewer.className='gallery-dialog'; viewer.innerHTML=`<button aria-label="Close">×</button><div class="dialog-grid">${imgs.map(i=>`<img src="${i.src}" alt="">`).join('')}</div>`; document.body.appendChild(viewer); viewer.showModal(); viewer.querySelector('button').onclick=()=>viewer.close(); viewer.addEventListener('close',()=>viewer.remove());}));
})();
